### PR TITLE
Add filter by Key-Values to annotate page

### PR DESCRIPTION
**Pull request by will-moore**
A few updates for Paris workshop...

### CODE REVIEW

**Comment by pwalczysko** [comment]
Add a bullet point ``Key-Value Pairs`` to https://github.com/ome/omero-guide-introduction/pull/2/commits/de750d7fd65a13bdfa3e6d5b5e64d2c382a8a08f#diff-d71714cfb87259199fdd76f111d37bd7R26


Screen Shot 2020-02-27 at 11 45 43

**Comment by pwalczysko** [comment]
This reads well, I added further tweaks in a PR opened against your branch @will-moore , see https://github.com/will-moore/omero-guide-introduction/pull/1 please.

**Comment by jburel** [comment]
@will-moore  if you can integrate @pwalczysko PR I will then merge and bump the submodule

**Comment by will-moore** [comment]
@jburel Done

**Comment by jburel** [comment]
Thanks

**Pull request merged**
